### ISSUE TITLE
support BIOBANK_FLAG facts?

### ISSUE THREAD

**Issue by dckc** [SCILHS/i2p-transform#2]
We have biospecimen info in our i2b2 fact table, but we don't see any support for getting it into the PCORnet BIOBANK_FLAG column. The column seems to default to 'N' with no code to do otherwise.

For reference:
- [bsr_i2b2_transform.sql](https://informatics.kumc.edu/work/browser/heron_load/bsr_i2b2_transform.sql) in HERON ETL

and [PCORNetLoader_ora.sql line 748](https://github.com/SCILHS/i2p-transform/blob/master/Oracle/PCORNetLoader_ora.sql#L748)

``` sql
CREATE TABLE pmndemographic(
    PATID varchar(50) NOT NULL,
    BIRTH_DATE date NULL,
    BIRTH_TIME varchar(5) NULL,
    SEX varchar(2) NULL,
    HISPANIC varchar(2) NULL,
    BIOBANK_FLAG varchar(1) DEFAULT 'N',
    RACE varchar(2) NULL,
    RAW_SEX varchar(50) NULL,
    RAW_HISPANIC varchar(50) NULL,
    RAW_RACE varchar(50) NULL
)
```

**Comment by dckc** [comment]
cc @njgraham @rwaitman @mprittie

**Comment by jklann** [comment]
Good point! The ontology should work fine - the default release never returns yes, but it should be straightforward to add it to the concept dimension and return yes when specimens are available. There is no need for a "No" ontology item because that is the inverted "Yes" panel.

However, you are correct, it looks like extracting that data didn't make it into the transform. Keep the issue open and I'll get to it when I can, or take a hack yourself. It hasn't been a high priority since PCORI isn't yet doing anything with biobanking specimens.

**Comment by dckc** [comment]
Yes, we may take a go at it, but this isn't yet a priority for us either.

**Comment by matthewjoss** [comment]
I added biobank_flag support at the end of the demographics section of the loader script in MSSQL, but not in Oracle yet. So now after running the transform, pmndemographic should have a 'Y' value for individuals with a positive biobank flag originating from the observation fact table.

**Comment by matthewjoss** [comment]
I added bio and flag support to the oracle loader script. Closing issue

**Comment by matthewjoss** [comment]
_bio bank flag support_
