### ISSUE TITLE
Implement run script

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2p-transform#40]
Split out the transform code from parameterization of the run, as in MSSQL run.sql

**Comment by matthewjoss** [comment]
done

**Comment by dckc** [comment]
Looks like this was fixed in 0e0da8c3f3c2961c94cae341944ffdd9c6e5b921 .

It's helpful to collaborators such as myself if you reference issues in commit messages... or at least reference the commit when you close an issue.

You can even [automatically close issues via commit messages](https://help.github.com/articles/closing-issues-via-commit-messages/)
