### ISSUE TITLE
PCORnet V3 table names

### ISSUE THREAD

**Issue by hestiri** [SCILHS/i2p-transform#50]
I figured that 3 of the PCORnet tables are named different from the name used in the PCORnet v3 data model. The 3 tables are:
current name                       data model name
labresults_cm     -->           lab_result_cm
death_cause       -->           death_condition
procedure           -->           procedures
Please change these names to the data model name.

**Comment by jklann** [comment]
@matthewjoss , let's add some table aliases with the correct table names and no pmn prefix. e.g., pmn_labresults_cm -> lab_result_cm

**Comment by matthewjoss** [comment]
I spoke with Jeff, and he meant for me to add some new synonyms. I updated the transform, but it turns out that tow of these (lab results and procedures) already had the correct synonyms in the transform and in the PopMedNet database. I added the death_condition synonym and push it up to github. Does this solve your problem?

**Comment by jklann** [comment]
@matthewjoss - Let's also rename the tables with a pmn prefix to the correct name, but also add synonyms for the misspelled versions so old tools still work....

**Comment by jklann** [comment]
Matt fixed this.
